variables:
    AUDIT_AWS_ELB_ALERT_LIST:
        description: "Which alerts would you like to check for? (Default is all ELB alerts)"
        required: true
        type: array
        default:
          - elb-old-ssl-policy
          - elb-current-ssl-policy
          - elb-inventory
    AUDIT_AWS_ELB_REGIONS:
         description: "List of AWS regions to check. Default is us-east-1,us-west-1,us-west-2,eu-west-1."
         required: true
         type: array
         default:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - eu-west-1
